### ISSUE TITLE
Not sure what is supposed to be the output

### ISSUE THREAD

**Issue by sabatale** [giseldo/chatbot_BTA_BPMN_to_AIML#2]
Hey there,

I was curious about your project but I can't seem to understand how to use it. I've loaded a diagram just for fun and was expecting the bot to be able to give answers based on the step content, but it doesn't look like it's working.

I understand the program converts BPMN to AIML somehow, but what is the purpose of the bot exactly? It doesn't look like it has any base vocabulary (hello, olà, etc.), so what exactly is the bot supposed to answer?

Thanks!

[diagram-with-colors.zip](https://github.com/giseldo/chatbot_ari_bpmn_to_aiml/files/4118097/diagram-with-colors.zip)

**Comment by giseldo** [comment]
Hi, thank you for your reply.

Instead of writing in aiml you write in bpmn. 

Your diagram will generate a dialog as follows

USER: NOTICES QR CODE
BOT: SCAN QR CODE
BOT: SCAN SUCCESSFUL?
USER: NO
BOT: OPEN PRODUCT INFORMATION IN MOBILE APP
BOT: IS INFORMED

The dialogue is meaningless with the text of the elements in the diagram that were used, but using other texts in another diagram can be easier to understand.


I will load some english examples and put on wiki.
https://github.com/giseldo/chatbot_ari_bpmn_to_aiml/wiki/
Did you understand?
Ask some other thing if the response was not enough.

**Comment by sabatale** [comment]
All is clear, thanks. I didn't realize starting from the first step was a requirement, but I get it now :)

**Comment by giseldo** [comment]
Happy to help,

Some notes:

Start Event and Gateway are elements that wait for the user do a input. The other elements: task and end_event are the output of the bot.

Also you can save the response of the user for later use in the diagram (for this use a comment in the gateway with the character $ in the start of the variable name. example: $varname). Later you can use the varname in task example: "you selected $varname", (don't use wildcards in the var name).

There is a technical document with the conversion explanined that i will put in wiki too later.
